library(devtools)
library(usethis)
library(pkgload)
library(pkgbuild)
library(pkgdown)

pkgload::load_all()
document()
devtools::test()
build(vignettes = FALSE)
check(vignettes = FALSE)
install(".")
pkgload::load_all()
detach("package:metamet", unload = TRUE)
pkgdown::build_site()
pak::pkg_remove("metamet")
